In [42]:
import numpy as np
import pandas as pd

In [43]:
df_train = pd.read_csv('./data/train.csv')


In [44]:
df_train.iloc[10]

make                                 rolls-royce
model                     phantom_drophead_coupe
year                                        2015
engine_fuel_type     premium_unleaded_(required)
engine_hp                                  453.0
engine_cylinders                            12.0
transmission_type                      automatic
driven_wheels                   rear_wheel_drive
number_of_doors                              2.0
market_category        exotic,luxury,performance
vehicle_size                               large
vehicle_style                        convertible
highway_mpg                                   19
city_mpg                                      11
popularity                                    86
Name: 10, dtype: object

In [45]:
def dot(xi, w):
  n = len(xi)

  result = 0.0

  for j in range(n):
    result += xi[j] * w[j]

  return result


In [46]:
xi = [453, 11, 86]
w0 = 7.17
w = [0.01, 0.04, 0.002]

In [47]:
def linear_regression(xi):
  return w0 + dot(xi, w)


In [48]:
linear_regression(xi)

12.312000000000001

In [49]:
w_new = [w0] + w
w_new

[7.17, 0.01, 0.04, 0.002]

In [50]:
def linear_regression(xi):
  xi = [1] + xi
  return dot(xi, w_new)

In [51]:
linear_regression(xi)

12.312

In [52]:
xi = [453, 11, 86]
w0 = 7.17
w = [0.01, 0.04, 0.002]

In [54]:
x1 = [1, 148, 24, 1385]
x2 = [1, 132, 25, 2031]
x10 = [1, 453, 11, 86]

X = [x1, x2, x10]
X = np.array(X)
X

array([[   1,  148,   24, 1385],
       [   1,  132,   25, 2031],
       [   1,  453,   11,   86]])

In [55]:
X.dot(w_new)

array([12.38 , 13.552, 12.312])

In [56]:
def linear_regression(X):
  return X.dot(w_new)

In [57]:
linear_regression(X)

array([12.38 , 13.552, 12.312])