In [25]:
import numpy as np
import pandas as pd

In [26]:
X = [
  [148, 24, 1385], 
  [132, 25, 2031], 
  [453, 11, 86], 
  [148, 24, 1385], 
  [132, 25, 2031], 
  [453, 11, 86], 
  [148, 24, 1385], 
  [132, 25, 2031], 
  [453, 11, 86], 
]

X = np.array(X)
X

y = [245, 312, 279, 245, 312, 279, 245, 312, 279]
y = np.array(y)

In [27]:
ones = np.ones(X.shape[0])
X = np.column_stack([ones, X])
X

array([[1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 2.500e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 1.100e+01, 8.600e+01],
       [1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 2.500e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 1.100e+01, 8.600e+01],
       [1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 2.500e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 1.100e+01, 8.600e+01]])

In [28]:
XTX = X.T.dot(X)
XTX

array([[9.0000000e+00, 2.1990000e+03, 1.8000000e+02, 1.0506000e+04],
       [2.1990000e+03, 7.3361100e+05, 3.5505000e+04, 1.5360900e+06],
       [1.8000000e+02, 3.5505000e+04, 3.9660000e+03, 2.5488300e+05],
       [1.0506000e+04, 1.5360900e+06, 2.5488300e+05, 1.8151746e+07]])

In [29]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.72219731e+14, -1.34113970e+12, -3.32963104e+13,
         1.83251938e+10],
       [-1.34113970e+12,  1.85005059e+09,  4.59309786e+10,
        -2.52788995e+07],
       [-3.32963104e+13,  4.59309786e+10,  1.14032276e+12,
        -6.27596130e+08],
       [ 1.83251938e+10, -2.52788995e+07, -6.27596130e+08,
         3.45408262e+05]])

In [30]:
XTX.dot(XTX_inv)

array([[ 1.65982819e+00,  9.13172960e-04,  4.50365543e-02,
        -3.55443917e-05],
       [ 2.39609352e+02,  9.74233419e-01,  4.95376039e+00,
        -4.99057909e-03],
       [ 2.17351799e+01, -2.04397589e-02,  9.10191417e-01,
         1.32609857e-04],
       [ 2.12983772e+02, -3.06521356e-02,  1.78298829e+01,
         9.67719041e-01]])

In [31]:
XTX.dot(XTX_inv).round(2)

array([[ 1.6600e+00,  0.0000e+00,  5.0000e-02, -0.0000e+00],
       [ 2.3961e+02,  9.7000e-01,  4.9500e+00, -0.0000e+00],
       [ 2.1740e+01, -2.0000e-02,  9.1000e-01,  0.0000e+00],
       [ 2.1298e+02, -3.0000e-02,  1.7830e+01,  9.7000e-01]])

In [34]:

w_full = XTX_inv.dot(X.T).dot(y)
w_full

array([ 6.17220772e+02, -9.54577066e-02, -1.35931996e+01,  1.21559042e-01])

In [35]:
w0 = w_full[0]
w = w_full[1:]
w0, w

(np.float64(617.2207717895508),
 array([ -0.09545771, -13.59319961,   0.12155904]))

In [38]:
def train_linear_regression(X, y):
  ones = np.ones(X.shape[0])
  X = np.column_stack([ones, X])

  XTX = X.T.dot(X)
  XTX_inv = np.linalg.inv(XTX)
  w_full = XTX_inv.dot(X.T).dot(y)
  
  w0 = w_full[0]
  w = w_full[1:]
  return w0, w

In [40]:
X = [
  [148, 24, 1385], 
  [132, 25, 2031], 
  [453, 11, 86], 
  [148, 24, 1385], 
  [132, 25, 2031], 
  [453, 11, 86], 
  [148, 24, 1385], 
  [132, 25, 2031], 
  [453, 11, 86], 
]

X = np.array(X)
X


y = [245, 312, 279, 245, 312, 279, 245, 312, 279]
y = np.array(y)

train_linear_regression(X, y)

(np.float64(617.2207717895508),
 array([ -0.09545771, -13.59319961,   0.12155904]))