In [1]:
import numpy as np

In [5]:
arr = np.array([[2, 3, 4], [4, 5, 6], [7, 8, 9]])
arr

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Element-wise Operations

arr = arr + 1   # Adds 1 to each element
arr

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
arr = arr * 2   # Multiplies each element by 2
arr
# Similar operations for division and exponentiation

array([[ 6,  8, 10],
       [10, 12, 14],
       [16, 18, 20]])

In [9]:
# Element-wise Operations with Two Arrays

arr1 = np.ones(4)
print(arr1)

arr2 = np.full(4, 3)
print(arr2)

result = arr1 + arr2  # Element-wise addition
result 



[1. 1. 1. 1.]
[3 3 3 3]


array([4., 4., 4., 4.])

In [11]:
result = arr1 / arr2  # Element-wise division
result


array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [12]:
# Comparison Operations
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]
greater_than_2

array([False, False,  True,  True])

In [13]:
# Selecting Elements Based on Conditions
selected_elements = arr[arr > 1]  # Gets elements greater than 1
selected_elements

array([2, 3, 4])

In [14]:
# Summary Operations
min_value = arr.min()    # Minimum value
print(min_value)

max_value = arr.max()    # Maximum value
print(max_value)

sum_value = arr.sum()    # Sum of all elements
print(sum_value)

mean_value = arr.mean()  # Mean (average) value
print(mean_value)

std_deviation = arr.std()  # Standard deviation
print(std_deviation)

1
4
10
2.5
1.118033988749895
