In [19]:
import pandas  as pd
import numpy as np

In [3]:
pd.__version__

'2.3.2'

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [7]:
# Get unique values in the fuel_type column
unique_fuel_types = df['fuel_type'].unique()

# Get the count of unique fuel types
number_of_fuel_types = len(unique_fuel_types)

print("Unique fuel types:", unique_fuel_types)
print("Number of fuel types:", number_of_fuel_types)

Unique fuel types: ['Gasoline' 'Diesel']
Number of fuel types: 2


In [8]:
# Count columns with missing values
columns_with_nulls = df.isnull().sum()

# Get only columns that have at least one missing value
columns_with_nulls = columns_with_nulls[columns_with_nulls > 0]

print("Columns with missing values:")
print(columns_with_nulls)
print("\nTotal number of columns with missing values:", len(columns_with_nulls))

Columns with missing values:
num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

Total number of columns with missing values: 4


In [9]:
# Filter for cars from Asia and find maximum fuel efficiency
max_efficiency_asia = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

print(f"Maximum fuel efficiency for cars from Asia: {max_efficiency_asia:.2f} mpg")

Maximum fuel efficiency for cars from Asia: 23.76 mpg


In [10]:
# Calculate median horsepower
median_horsepower = df['horsepower'].median()

print(f"Median horsepower: {median_horsepower:.1f}")

Median horsepower: 149.0


In [11]:
# Calculate mode of horsepower
mode_horsepower = df['horsepower'].mode()

print(f"Most frequent horsepower value(s): {mode_horsepower.values[0]}")

Most frequent horsepower value(s): 152.0


In [12]:
# Get the mode value from earlier
mode_value = df['horsepower'].mode().values[0]

# Fill missing values in horsepower column with the mode
df['horsepower'] = df['horsepower'].fillna(mode_value)

# Verify there are no more missing values in horsepower column
print("Number of missing values in horsepower after filling:", df['horsepower'].isnull().sum())

Number of missing values in horsepower after filling: 0


In [13]:
# Calculate median horsepower after filling missing values
median_horsepower_after = df['horsepower'].median()

print(f"Median horsepower after filling missing values: {median_horsepower_after:.1f}")

Median horsepower after filling missing values: 152.0


In [14]:
# Select cars from Asia
asian_cars = df[df['origin'] == 'Asia']

# Display the selected cars
print("Cars from Asia:")
print(asian_cars)

# Also show the count of Asian cars
print(f"\nTotal number of cars from Asia: {len(asian_cars)}")

Cars from Asia:
      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia 

In [15]:
# Select specific columns for all cars
selected_columns = df[['vehicle_weight', 'model_year']]

# Display the selected columns
print("Vehicle weights and model years:")
print(selected_columns)

# Show the number of rows
print(f"\nTotal number of cars: {len(selected_columns)}")

Vehicle weights and model years:
      vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]

Total number of cars: 9704


In [16]:
# Select first 7 rows from the selected columns
first_seven = selected_columns.head(7)

# Display the first 7 rows
print("First 7 cars (vehicle weights and model years):")
print(first_seven)

First 7 cars (vehicle weights and model years):
   vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012


In [17]:
# Convert DataFrame to NumPy array
X = selected_columns.values

# Display the array shape and contents
print("Array shape:", X.shape)
print("\nArray contents:")
print(X)

Array shape: (9704, 2)

Array contents:
[[3413.43375861 2003.        ]
 [3149.66493422 2007.        ]
 [3079.03899737 2018.        ]
 ...
 [2583.47131761 2008.        ]
 [2905.52738998 2011.        ]
 [2908.04347736 2005.        ]]


In [24]:
# Compute matrix multiplication of X transpose and X
XTX = X.T @ X

# Display the result
print("Shape of XTX:", XTX.shape)
print("\nMatrix multiplication result (X.T @ X):")
print(XTX)

Shape of XTX: (2, 2)

Matrix multiplication result (X.T @ X):
[[8.98159673e+10 5.85831378e+10]
 [5.85831378e+10 3.92634741e+10]]


In [20]:
# Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Display the result
print("Shape of XTX_inv:", XTX_inv.shape)
print("\nInverse matrix (XTX_inv):")
print(XTX_inv)

Shape of XTX_inv: (2, 2)

Inverse matrix (XTX_inv):
[[ 4.15473853e-10 -6.19908516e-10]
 [-6.19908516e-10  9.50404590e-10]]


In [21]:
# Create array y with given values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Display the array
print("Array y:")
print(y)

# Show the shape of the array
print("\nShape of y:", y.shape)

Array y:
[1100 1300  800  900 1000 1100 1200]

Shape of y: (7,)


In [31]:
# Use first 7 rows of X to match y dimensions
X = first_seven.values

# Recompute XTX with the 7 rows
XTX = X.T @ X

# Recompute inverse
XTX_inv = np.linalg.inv(XTX)

# Now compute w with matching dimensions
w = XTX_inv @ X.T @ y

# Display the result
print("Shape of w:", w.shape)
print("\nWeight vector w:")
print(w)

Shape of w: (2,)

Weight vector w:
[0.07099685 0.41931263]


In [32]:
# Calculate sum of weights
w_sum = w.sum()

print(f"Sum of weights: {w_sum:.6f}")

Sum of weights: 0.490309
