In [1]:
import numpy as np

In [2]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ones_array = np.ones(10)
ones_array


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
constant_array = np.full(10, 3)
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
# Converting Lists to Arrays
my_list = [2, 3, 4]
array_from_list = np.array(my_list)
array_from_list

array([2, 3, 4])

In [8]:
# Generating Ranges of Numbers
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating Arrays with Linear Spacing
linspace_array = np.linspace(0, 1, 11) # create 11 numbers from 0 to 1
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
# Multi-dimensional Arrays

zeros_matrix = np.zeros((5, 2))
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
ones_matrix = np.ones((5, 2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [17]:
# Indexing and Slicing Arrays

arr = np.array([[2, 3, 4], [4, 5, 6]])
arr 


array([[2, 3, 4],
       [4, 5, 6]])

In [18]:
first_row = arr[0]
first_row

array([2, 3, 4])

In [16]:
first_col = arr[:, 0]
first_col

array([2, 4])

In [ ]:
# Generating Random Arrays

np.random.seed(2)
random_array = np.random.rand(5, 2) # generates random numbers between 0 and 1
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])